#!/usr/bin/env mksh

set -euo pipefail


error_msg() {
(
typeset -r msg="$1"
shift

printf 'USER="%s"; DATE="%s"; MSG="%s"' "$USER_ID" "$(date)" "$msg"

while (( $# > 1 )); do
printf '; %s="%s"' "$1" "$2"
shift 2
done
printf "\n"
) >&2
}


fatal() {
error_msg "$@"
exit 1
}


if (( USER_ID )); then fatal 'this script must be executed as root'; fi


WEBROOT='/var/www'
NGX_ROOT='/etc/nginx'
NGX_SITES_AVAILABLE='/etc/nginx/sites-available'
NGX_SITES_ENABLED='/etc/nginx/sites-enabled'

if ! [ -d "$NGX_SITES_AVAILABLE" ]; then mkdir -p "$NGX_SITES_AVAILABLE"; fi
if ! [ -d "$NGX_SITES_ENABLED" ]; then mkdir -p "$NGX_SITES_ENABLED"; fi


ngx_config() {
typeset -r site="$1"
typeset -r root="$2"

typeset -r site_available="$NGX_SITES_AVAILABLE/$site"
typeset -r site_enabled="$NGX_SITES_ENABLED/$site"

if [ -f "$site_available" ]; then
fatal 'existing sites-available entry' 'site' "$site"
fi

if [ -L "$site_enabled" ]; then
fatal 'existing symlink to site' 'site' "$site"
fi

cat - <<EOF > "$site_available"
server {
	server_name $site;
	root        $root;

	client_max_body_size 8M;
	send_timeout        540;

	location / {
	}
}
EOF

ln -s "$site_available" "$site_enabled"
}


website() {
typeset -r site="$1"
typeset -r root="$WEBROOT/$site"
shift

if [ -d "$root" ]; then
error_msg 'warning: website root already exists, ignoring it.' \
'name' "$site" \
'root' "$root"
else
mkdir -p "$root"
chown -R 'nginx:nginx' "$root"

# copy files from user specified directories if any
typeset site_contents
while (( $# > 0 )); do
site_contents="$(realpath "$1")"
if ! [ -d "$site_contents" ]; then
fatal 'specified site contents directory does not exist or is not a directory' \
'site' "$site" \
'directory' "$site_contents"
fi

rsync -av --chown='nginx:nginx' "$(realpath "$1")/" "$root/"
shift
done
fi

ngx_config "$site" "$root"

if ! nginx -t; then
fatal 'nginx config test failed, please verify the output' \
'site' "$site" \
'root' "$root"
fi

# this also restarts ngx automatically
if ! certbot; then
fatal 'certbot failed to run, please verify the output'
fi
}

# cleanup a possibly dirty website installation
down() {
typeset -r site="$1"
typeset -r root="$WEBROOT/$site"

typeset -r enabled_site="$NGX_SITES_ENABLED/$site"
typeset -r available_site="$NGX_SITES_AVAILABLE/$site"

if [ -d "$root" ]; then
rmdir "$root" || \
error_msg \
'website root exists and is not an empty directory, '\
'please verify the directory to avoid losing data' \
'site' "$site" \
'root' "$root"
fi

[ -L "$enabled_site" ] && rm "$enabled_site"
[ -f "$available_site" ] && rm "$available_site"

return 0
}

# === Websites come here ===

# ( website / down ) ( entry ) [ directories ... ]
#
# * website: defines an entry, copying files from [ directories ... ]
# * down:    non-destructively removes an entry

website blog.rodrigo.linhazero.com /home/rodrigo/blog
